truncate table restaurant.customer_order;
truncate table restaurant.order_menu;
truncate table restaurant.sub_order;
truncate table restaurant.tbl_kitchen_order;
truncate table restaurant.bill_card_payment;
truncate table restaurant.multipay_bill;
truncate table restaurant.bill;
truncate table restaurant.tbl_cashregister;
truncate table restaurant.table_details;